version: '3'
services:
  service1:
    image: service1
    build: 
       context: .
       dockerfile: Dockerfile_service1
    ports:
      - "80:80"
  service2:
    image: service2
    build:
      context: .
      dockerfile: Dockerfile_service2
    ports:
      - "5050:5050"